language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DB=sqlite
sqlite:
  adapter: sqlite3
  database: krusty.db
  timeout: 500
cache:
  directories:
    - $HOME/.pip-cache/
before_install:
  - export PIP_USE_MIRRORS=true
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt --cache-dir $HOME/.pip-cache
script:
  - python test/supply.py
  - python test/manufacture.py
